### PR TITLE
[Merged by Bors] - Switch CI docker container from hard-coded tag to `v1` tag

### PR DESCRIPTION
**Pull request by x3ro**
[This commit](https://github.com/xaynetwork/xayn_docker/commit/f3bcb13d6ec3bdb0d14178106443caf3c6ca244b) from the `xayn_docker` repo adds rsync and allows the `release` tag to be created.

### CODE REVIEW

**Comment by acrrd** [comment]
Why call it `release` and not `latest`? `release` has a stronger meaning and are not attaching versioning to it.

**Comment by x3ro** [comment]
I chose something else than latest because it's easy to accidentally tag things `latest`, as it's the docker default. I wanted to explicitly prevent this error scenario, where e.g. a local build or a modification in the pipeline accidentally overwrites the `latest` tag. In addition, `latest` would also be wrong semantically, as the `release` tag is manually generated (similar to the release job in the discovery engine), so it would not be `latest` most of the time.

**Comment by acrrd** [comment]
Another question. How would be the workflow when a PR needs to update the image with a change that is not backward compatible? If we update the image other PRs will fail but them cannot rebased yet. Do we have a nice solution for this or we hope that this will not happen that often to create significant problem?

**Comment by x3ro** [comment]
I think in that case I would create a new tag, e.g. `release-v2` or something like that, which would then allow us to do successive updates in the pipelines. If we discover that something like this happens regularly in the future, we could also think about a more elaborate tagging scheme (e.g. semver like), but I think that this would currently not be worth the effort.

**Comment by acrrd** [comment]
Should we then start with `v1` (without the 'release' part, it don't think it adds much value if we have the version) and bump it when we have a breaking change?

**Comment by x3ro** [comment]
Sure, let's go with that.

**Comment by x3ro** [comment]
borst try-

**Comment by x3ro** [comment]
bors try

**Comment by x3ro** [comment]
bors try-

**Comment by x3ro** [comment]
bors try

**Review by Robert-Steiner — APPROVED** [review]
🚀

**Comment by x3ro** [comment]
bors merge

**Review by acrrd — APPROVED** [review]

**Comment by x3ro** [comment]
bors merge-

**Comment by x3ro** [comment]
bors merge

**Comment by x3ro** [comment]
bors merge-

**Comment by x3ro** [comment]
bors merge

**Pull request closed without merging**
