### PR TITLE
[Merged by Bors] - TY 2489 Exclude arm64 for ios simulator

### PR DESCRIPTION
**Pull request by acrrd**

### CODE REVIEW

**Comment by Robert-Steiner** [comment]
I saw that blue already merged the fix where they exclude the arm64 simulator on their side. just wanted to note that your fix would also work (at least it worked for our example)

**Comment by acrrd** [comment]
We are going to add this exclusion and we will remove it when we can compile for aarch64-apple-ios-sim.

**Review by Robert-Steiner — APPROVED** [review]
can you please also remove those lines in `discovery_engine_flutter/example/ios/Podfile`
```
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386 arm64'
    end
```

**Review by Robert-Steiner — APPROVED** [review]

**Comment by acrrd** [comment]
bors merge

**Pull request closed without merging**
