### PR TITLE
[Merged by Bors] - TY 2493 discard net error on init

### PR DESCRIPTION
**Pull request by acrrd**

### CODE REVIEW

**Review by rustonaut — APPROVED** [review]
lgtm

I wonder if there is a standard style for ignoring results in rust.

Thinks I have seen include:

- `drop`
- `let _ = ...;`
- `.ok()` 

I guess the last one is a bit more explicit and doesn't "remove"
potential `must_use` of the `Ok` type :thinking:

**Comment by acrrd** [comment]
> lgtm
> 
> I wonder if there is a standard style for ignoring results in rust.
> 
> Thinks I have seen include:
> 
>     * `drop`
> 
>     * `let _ = ...;`
> 
>     * `.ok()`
> 
> 
> I guess the last one is a bit more explicit and doesn't "remove" potential `must_use` of the `Ok` type thinking

clippy suggest to use `drop` because `let _ = ` does the same and is more explicit.
Didn't thought about about `ok` but it remove the must_use on the inner type because it will be hidden in a option so
`Result<Result<_, _>, _>::ok()` does not trigger the lint.

Allowing the linter also does not work. I think `drop` is a bit more explicit then converting to an option.

**Comment by Robert-Steiner** [comment]
i have added a test for that in #166

**Comment by acrrd** [comment]
bors merge

**Comment by acrrd** [comment]
bors merge

**Pull request closed without merging**
