### PR TITLE
[Merged by Bors] - TY-2435 add page param to news query

### PR DESCRIPTION
**Pull request by finiteprods**
**Summary**

adds a `page` field to the `NewsQuery` struct and updates the `news` method to begin supporting active search.

### CODE REVIEW

**Review by janpetschexain — APPROVED** [review]
lgtm

i'm lacking some overview of the providers, why is the task only about adding `page` to `NewsQuery` but not to `HeadlinesQuery` as well? it looks to me like the same reasoning applies for both, regarding the possibly too slowly changing content mentioned in the daily.

**Comment by finiteprods** [comment]
> why is the task only about adding `page` to `NewsQuery` but not to `HeadlinesQuery` as well?

fair question @acrrd is it needed for headlines?

**Comment by acrrd** [comment]
> fair question @acrrd is it needed for headlines?

Because we cannot do custom query on the headlines.

**Comment by finiteprods** [comment]
bors merge

**Pull request closed without merging**
