### PR TITLE
[Merged by Bors] - TY-2993 use wildcard on empty filter

### PR DESCRIPTION
**Pull request by rustonaut**
**References:**

- [TY-2993](https://xainag.atlassian.net/browse/TY-2993)

### CODE REVIEW

**Review by Robert-Steiner — APPROVED** [review]
the `test_filter_empty` test needs to be removed or we remove `test_empty_filter_is_wildcard` and adjust `test_filter_empty`. 
I will already approve it though

**Comment by rustonaut** [comment]
thanks, I already did fix that :sweat:
I just ran into something else and then forgot to push.

**Comment by rustonaut** [comment]
bors merge

**Comment by abargiela** [comment]
bors cancel

**Comment by abargiela** [comment]
bors merge

**Comment by abargiela** [comment]
bors cancel

**Comment by abargiela** [comment]
bors cancel

**Comment by abargiela** [comment]
bors try

**Comment by janpetschexain** [comment]
> @abargiela uhm, can I try running bors merge? Or bors cancel? It seems to be stuck in a strange way 🤔

the pending bors is an artifact, just call `bors merge` and it will run properly

**Pull request closed without merging**
