### PR TITLE
[Merged by Bors] - ET-4478 replace custom with stabilized total float cmp

### PR DESCRIPTION
**Pull request by janpetschexain**
**Reference**

- [ET-4478]
- https://github.com/xaynetwork/xayn_discovery_engine/pull/937#discussion_r1189954142

**Summary**

- replace our custom `nan_safe_f32_cmp()` with the stabilized `f32::total_cmp()`
- cleanup remaining `coi::utils`

[ET-4478]: https://xainag.atlassian.net/browse/ET-4478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by rustonaut — APPROVED** [review]
lgtm

**Comment by janpetschexain** [comment]
bors merge

**Comment by janpetschexain** [comment]
bors cancel

**Comment by janpetschexain** [comment]
bors merge

**Pull request closed without merging**
