### PR TITLE
[Merged by Bors] - TY-2644 switch linux based ci builds to hetzner

### PR DESCRIPTION
**Pull request by x3ro**

### CODE REVIEW

**Review by rustonaut — APPROVED** [review]
lgtm,

through is the instrumentation still done by github on their system? If so then
I'm not sure if running  the selection and "ok" jobs on hetzner makes any sense.

**Comment by x3ro** [comment]
The advantage is that they start the jobs faster. The GitHub runners sometimes take some time to become available / spin up, whereas our dedicated CI runners will always be immediately available (with some priority tweaking, admitedly :D). But you're correct in that the advantage will not be big.

**Comment by x3ro** [comment]
bors merge

**Comment by x3ro** [comment]
bors merge-

**Comment by x3ro** [comment]
bors merge

**Comment by x3ro** [comment]
bors merge-

**Comment by x3ro** [comment]
bors merge

**Comment by x3ro** [comment]
bors merge-

**Comment by x3ro** [comment]
bors merge

**Pull request closed without merging**
