### PR TITLE
[Merged by Bors] - TY-2773 port layer crate to DE conventions

### PR DESCRIPTION
**Pull request by janpetschexain**
**References**

- [TY-2773]

**Summary**

- rename the crate in the first commit
- fix one lint at a time in the following commits

[TY-2773]: https://xainag.atlassian.net/browse/TY-2773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by rustonaut — APPROVED** [review]
lgtm

**Review by rustonaut — APPROVED** [review]
lgtm

**Comment by janpetschexain** [comment]
bors merge

**Comment by janpetschexain** [comment]
bors cancel

**Comment by janpetschexain** [comment]
bors merge

**Pull request closed without merging**
