### PR TITLE
[Merged by Bors] - TY-2468 newcatcher mock server

### PR DESCRIPTION
**Pull request by Robert-Steiner**
Ticket:
- [TY-2468]

[TY-2468]: https://xainag.atlassian.net/browse/TY-2468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by biernacki — APPROVED** [review]
lgtm!

**Comment by Robert-Steiner** [comment]
@biernacki I going to move the code into `discovery_engine/test/integration`

**Comment by Robert-Steiner** [comment]
done

**Comment by Robert-Steiner** [comment]
bors merge

**Pull request closed without merging**
