### PR TITLE
[Merged by Bors] - TY-2458, TY-2452 Excluded sources events and repository

### PR DESCRIPTION
**Pull request by biernacki**
[events](https://xainag.atlassian.net/browse/TY-2458)
[repository](https://xainag.atlassian.net/browse/TY-2452)

This PR adds events and repository (with Hive implementation and tests) to manage excluded sources.

### CODE REVIEW

**Review by Robert-Steiner — APPROVED** [review]
looks good 👍

**Comment by biernacki** [comment]
> looks good 👍

all should be fixed, please check again

**Review by Robert-Steiner — APPROVED** [review]
🚀

**Comment by biernacki** [comment]
bors merge

**Pull request closed without merging**
