### PR TITLE
[Merged by Bors] - Remove unused parameter from release CI

### PR DESCRIPTION
**Pull request by acrrd**
Remove unused parameter to the release script.
Fix commit message.

### CODE REVIEW

**Comment by acrrd** [comment]
https://github.com/xaynetwork/xayn_discovery_engine/runs/5114789966?check_suite_focus=true

**Review by Robert-Steiner — APPROVED** [review]

**Comment by acrrd** [comment]
bors merge

**Comment by acrrd** [comment]
bors cancel

**Comment by acrrd** [comment]
bors merge

**Pull request closed without merging**
