### PR TITLE
[Merged by Bors] - TY-2396 TY-2355 Remove unused code

### PR DESCRIPTION
**Pull request by acrrd**
Remove `ResetEngine` event.
Remove `SearchType`.
Remove `nonPersonsonalizedRank`.
Rename `personalizedRank` to `batchIndex`.

### CODE REVIEW

**Review by janpetschexain — COMMENTED** [review]
there are some related things left, should those be removed as well?

for reset engine:
- these [mocks](https://github.com/xaynetwork/xayn_discovery_engine/blob/TY-2396_remove_unsed_code/discovery_engine/test/codecs/mocks.dart) have closures for the reset
- these [mocks](https://github.com/xaynetwork/xayn_discovery_engine/blob/TY-2396_remove_unsed_code/discovery_engine/test/discovery_engine/utils/utils.dart) have a reset engine respose event
- these [docs](https://github.com/xaynetwork/xayn_discovery_engine/blob/TY-2396_remove_unsed_code/docs/events.md) mention the event

for search type:
- these [docs](https://github.com/xaynetwork/xayn_discovery_engine/blob/TY-2396_remove_unsed_code/docs/events.md) mention the type

for batch index:
- some types for example like `Article` and `NewsResource` have a `rank` field, should this also be replaced by `batch_index`?

**Comment by acrrd** [comment]
> there are some related things left, should those be removed as well?
> 
> for reset engine:
> 
>     * these [mocks](https://github.com/xaynetwork/xayn_discovery_engine/blob/TY-2396_remove_unsed_code/discovery_engine/test/codecs/mocks.dart) have closures for the reset
> 
>     * these [mocks](https://github.com/xaynetwork/xayn_discovery_engine/blob/TY-2396_remove_unsed_code/discovery_engine/test/discovery_engine/utils/utils.dart) have a reset engine respose event
> 
>     * these [docs](https://github.com/xaynetwork/xayn_discovery_engine/blob/TY-2396_remove_unsed_code/docs/events.md) mention the event
> 
> 
> for search type:
> 
>     * these [docs](https://github.com/xaynetwork/xayn_discovery_engine/blob/TY-2396_remove_unsed_code/docs/events.md) mention the type

done.
 
> for batch index:
> 
>     * some types for example like `Article` and `NewsResource` have a `rank` field, should this also be replaced by `batch_index`?

No thi are two differen things. The `rank` is the page rank of the domain of the source. `batchIndex` is the position of the document in the batch we are returning to the app when requested.

**Review by janpetschexain — APPROVED** [review]
lgtm

**Comment by acrrd** [comment]
bors merge

**Review by janpetschexain — APPROVED** [review]

**Comment by janpetschexain** [comment]
bors cancel

**Comment by janpetschexain** [comment]
bors merge

**Pull request closed without merging**
