### PR TITLE
[Merged by Bors] - ET-4418 rename X-Tenant-Id => X-Xayn-Tenant-id

### PR DESCRIPTION
**Pull request by rustonaut**
Rename header to avoid conclusions.

**References:**

- story [ET-4411]
- issue [ET-4418]

[ET-4411]: https://xainag.atlassian.net/browse/ET-4411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-4418]: https://xainag.atlassian.net/browse/ET-4418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by rustonaut** [comment]
> It will avoid confusion in the code

It's not about confusion in the code but about middleware in out pipeline setting this header with a slightly different meaning. Except depending on various decisions our Infra Team  might make or not make it could not be a different meaning in the future for multi tenant deployments, we will have to see :shrug: 

So we might need to change it in the future again, we will see.

But it's a tenant id so we probably want to keep that naming part as far as possible.

Multi-app setups are a different approach (in my understanding) which can also be used to archive multi tenancy but AFIK we are currently going in a different direction so I would want to avoid such naming.

**Comment by rustonaut** [comment]
bors merge

**Comment by acrrd** [comment]
> It's not about confusion in the code but about middleware in out pipeline setting this header with a slightly different meaning. Except depending on various decisions our Infra Team might make or not make, it could not be a different meaning in the future for multi tenant deployments. We will have to see shrug
 
 We have to read it in the code and the debug request so it can create confusion for us.

**Comment by rustonaut** [comment]
> We have to read it in the code and the debug request so it can create confusion for us.

we want a tenant id it gives us a tenant id where is the confusions?

**Comment by rustonaut** [comment]
bors merge

**Pull request closed without merging**
